### ISSUE TITLE
Enable gh-pages for the repository

### ISSUE THREAD

**Issue by laurenkt** [JackoRo/SWEngProjectWideStandard#4]
If gh-pages is enabled for the repository on the master branch then we can use an absolute URI for the schema and it will be more validation friendly.

The URI would be [jackoro.github.io/swengprojectwidestandard](//jackoro.github.io/swengprojectwidestandard)

**Comment by JackoRo** [comment]
I tried doing this in the settings but it goes to a 404 error.
 https://jackoro.github.io/SWEngProjectWideStandard/

**Comment by JackoRo** [comment]
You can serve files but it doesn't have an index.html

**Comment by laurenkt** [comment]
Can fix that ! :)

**Comment by laurenkt** [comment]
I'll check what the requirements are exactly for schema URIs

**Comment by laurenkt** [comment]
Can you switch to the mode where it's master branch in a docs/ folder – then we can generate an HTML doc from the XSD annotations and put it in there

**Comment by JackoRo** [comment]
I can't because there is no /docs directory, will need to add one first.

**Comment by laurenkt** [comment]
Ah ok. I can get back to you after I set up the doc generation thing

**Comment by laurenkt** [comment]
Try now?

**Comment by JackoRo** [comment]
I've changed it and it allowed me to do.

**Comment by laurenkt** [comment]
Turns out it didn't need to rebuild, just I needed to get the case right in the path. Weird for URLs to be case-sensitive !! But hey. It works at https://jackoro.github.io/SWEngProjectWideStandard/ although it's a bit shit at the moment, will probs look better when we add more annotations and I tweak the stylesheet a bit. Anyway I'll close this issue now ! :) Thanks
